### PR TITLE
[MRG] Fork notebook handlers instead, add tests from jupyter_server

### PR DESCRIPTION
**Pull request by Zsailer**
After talking with @minrk last month, we came to the conclusion that it makes the most sense to *fork* notebook's handlers (rather than import). This enables us to increase our chances to address possible backward incompatibility issues as jupyter_server evolves and jupyter/notebook doesn't...

### CODE REVIEW

**Comment by Zsailer** [comment]
@echarles I think nbclassic's job is to keep the `/notebook` and `/tree` endpoints working with the old Notebook javascript and jupyter_server. 

If jupyter_server starts to diverge from the notebook server too much (i.e. REST API changes), then we (the broader Jupyter community) will have to decide if we want to update the Jupyter Notebook javascript to continue working with jupyter_server. If so, the compatibility changes will need to happen in jupyter/notebook. nbclassic is just a temporary fix until something like that arises...

**Comment by echarles** [comment]
Thx for this useful input @Zsailer. Further to our discussion at the jupyter server meeting, are you going to also pull the template files in this PR?

**Comment by Zsailer** [comment]
Yeah, I think I'll pull the templates in this PR before merging.

**Comment by Zsailer** [comment]
Decided to pull templates in a future PR. Merged this as-is to get #7 merged.

**Pull request merged**
